# Generated by Django 3.0.6 on 2020-05-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('links', models.ManyToManyField(to='linklist.Link')),
            ],
        ),
    ]
