# Generated by Django 3.0.6 on 2020-05-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.SlugField(max_length=200),
        ),
    ]
