# Generated by Django 3.0.7 on 2020-06-21 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linklist', '0002_linklist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linklist',
            name='user',
        ),
        migrations.AddField(
            model_name='linklist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linklists', to=settings.AUTH_USER_MODEL),
        ),
    ]
