# Generated by Django 3.0.6 on 2020-05-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklist', '0002_auto_20200529_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(),
        ),
    ]
