# Generated by Django 3.0.6 on 2020-06-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linklist', '0006_auto_20200530_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='Default title', max_length=200),
            preserve_default=False,
        ),
    ]
