# Generated by Django 3.0.6 on 2020-06-05 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linklist', '0007_link_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linklist',
            name='links',
        ),
        migrations.AddField(
            model_name='link',
            name='linklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linklist.LinkList'),
        ),
        migrations.AddField(
            model_name='linklist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 17, 12, 22, 765511, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
