# Generated by Django 3.0.6 on 2020-06-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linklist', '0008_auto_20200605_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='linklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linklist.LinkList'),
        ),
    ]
